routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */

Route::get('/clear-cache', function () {
    $exitCode = Artisan::call('cache:clear');
    return "Cache is cleared";
});

Route::get('/clear-config', function () {
    $exitCode = Artisan::call('config:clear');
    return "Configuration Cache is cleared";
});
Route::get('/clear-route', function () {
    $exitCode = Artisan::call('route:clear');
    return "Route Cache is cleared";
});

Route::get('/clear-view', function () {
    $exitCode = Artisan::call('view:clear');
    return "View Cache is cleared";
});
Route::get("/time", function () {
    return date("h:i:s a", $_SERVER['REQUEST_TIME']);
});

Route::get('scheduler', 'ArtisanController@handle');

Route::get('privacy', 'FrontEndController@privacy')->name('privacy');
Route::get('term-condition', 'FrontEndController@termOfCondition')->name('term-condition');
Route::get('/', 'HomeController@index')->name('home');

Route::resource('albums', 'AlbumsController');
Route::resource('photos', 'PhotosController');

// Socail Logins
Route::get('login/{provider}', 'SocailAuthController@redirectToProvider');
Route::get('login/{provider}/callback', 'SocailAuthController@handleProviderCallback');

Route::get('get-competition-detail', 'UserController@getDetailCompetition')->name('user.get-competition-detail');

Route::get('get-competiton-all/{cat}', 'UserController@show_all')->name('user.show-all');
Route::post('user/do-login', 'UserController@doLogin')->name('user.doLogin');
Route::post('user/verify-code', 'UserController@verifyPhoneNumber')->name('user.verify_phone_number');
Route::get('user/role', 'UserController@userRole')->name('user.role');
Route::post('user/do-register', 'UserController@doregister')->name('user.doRegister');
Route::post('user/add-user-detail', 'UserController@addUserDetail')->name('user.addUserDetail');
Route::get('get-states', 'UserController@getStates')->name('get-states');
Route::get('voting', ['as' => 'voting', 'uses' => 'UserController@votingMedia']);
Route::post('comment', ['as' => 'comment', 'uses' => 'CompetitionController@getCommentPost']);
Route::get('comment_all', ['as' => 'comment_all', 'uses' => 'CompetitionController@getAllCommentPost']);
Route::group(['middleware' => 'auth', 'prefix' => 'user', 'as' => 'user.'], function () {
    Route::get('do-logout', ['as' => 'doLogout', 'uses' => 'UserController@doLogout']);
    Route::get('dashboard', ['as' => 'dashboard', 'uses' => 'UserController@dashboard']);
    Route::post('competitions', ['as' => 'competitions', 'uses' => 'UserController@ShowDatatable']);
    Route::get('profile', ['as' => 'profile', 'uses' => 'UserFollowController@index']);
    Route::post('follow', ['as' => 'follow', 'uses' => 'UserFollowController@followUser']);
    Route::get('getShareableLink', ['as' => 'getShareableLink', 'uses' => 'UserController@getShareableLink']);
    Route::get('getShareableLinkCount', ['as' => 'getShareableLinkCount', 'uses' => 'UserController@getShareableLinkCount']);
    Route::get('getShareableLinkCountAll', ['as' => 'getShareableLinkCountAll', 'uses' => 'UserController@getShareableLinkCountAll']);

    Route::group(['prefix' => 'content', 'as' => 'content.'], function () {
        Route::post('add', ['as' => 'add', 'uses' => 'UserContentController@addContent'])->middleware(['role:user']);
        Route::get('get-genres', ['as' => 'get-genres', 'uses' => 'UserContentController@getGenres']);
        Route::post('add_like', ['as' => 'add_like', 'uses' => 'UserContentController@addUserLikes']);
        Route::post('judge', ['as' => 'judge', 'uses' => 'UserContentController@competitionUserJudge']);
        Route::get('get-user-competition', ['as' => 'get-user-competition', 'uses' => 'UserContentController@getUserCompetition']);
    });
    Route::group(['prefix' => 'competition', 'as' => 'competition.'], function () {
        Route::get('create', ['as' => 'create', 'uses' => 'CompetitionController@index'])->middleware(['role:user|fan|agent|sponsor']);
        Route::get('get-public-competition', ['as' => 'get-public-competition', 'uses' => 'CompetitionController@getPublicCompetition']);
        Route::get('get-public-competition-detail', ['as' => 'get-public-competition-detail', 'uses' => 'CompetitionController@getPublicCompetitionDetail']);
        Route::post('save', ['as' => 'save', 'uses' => 'CompetitionController@saveCompetion'])->middleware(['role:user|fan|agent|sponsor']);
        Route::get('private/join', ['as' => 'private_join', 'uses' => 'CompetitionController@joinPrivate']);
        Route::get('verify-code', ['as' => 'verify_code', 'uses' => 'CompetitionController@codeVerify']);
        Route::post('join_private_competition', ['as' => 'join_private_competition', 'uses' => 'CompetitionController@joinPrivateCompetition']);
        Route::post('join_public_competition', ['as' => 'join_public_competition', 'uses' => 'CompetitionController@joinPublicCompetition']);

    });
    Route::group(['prefix' => 'report', 'as' => 'report.'], function () {
        Route::post('save', ['as' => 'save', 'uses' => 'AbuseReportController@saveReport']);
    });
    Route::get('getAllActiveUsers', ['as' => 'getAllActiveUsers', 'uses' => 'HomeController@getUserDetails']);
});
Route::group(['prefix' => 'phone', 'as' => 'user.phone.'], function () {
    Route::post('send-verify', ['as' => 'send-verify', 'uses' => 'HomeController@sendVerifyCode']);
    Route::post('change_number', ['as' => 'change_number', 'uses' => 'HomeController@changeNumber']);
    Route::post('verify', ['as' => 'verify', 'uses' => 'HomeController@VerifyCode']);
});
/******************* Test Route *************/
Route::get('email-check', ['uses' => 'TestController@emailTest']);
Route::get('phone-test', ['uses' => 'TestController@phoneTest']);
Route::get('account-detail', ['uses' => 'TestController@index']);
Route::get('testing', ['uses' => 'TestController@competitionDetailForTesting']);
Route::get('video-test', ['uses' => 'TestController@videoTest']);
Route::get('pp', ['uses' => 'TestController@pp']);

resources/views/frontend/users/pages/modal/reporting-modal.blade.php
 
  <div class="modal fade" id="reportingModal" tabindex="-1" role="dialog" aria-labelledby="phoneVerification" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content theme-modal verification-modal" style="background: #940000">
        <div class="modal-header border-0 ">
          <button type="button" class="close px-2" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true" class="text-white">&times;</span>
          </button>
        </div>
        <div class="modal-body">

          <div class="container">
            <div class="row align-items-center justify-content-center">
              <div class="col-12 bg-red">
                <div class="row">
                  <div class="col-12 text-center">
                    <h3 class="text-white mb-4">Please select a problem below</h3>
                  </div>
                </div>
                <div class="row">
                  <div class="report_server_response col-12">
                  </div>
                </div>
                <div class="row">
                    @if(@$profanity)
	                    @foreach($profanity as $key => $value)
		                  <div class="col-md-4 mb-4 text-center">
		                    <button type="button" class="btn btn-primary rounded-pill report {{($key == 0) ? 'btn_reporting' : ''}}" data-value="{{$value->id}}">
		                      {{ucFirst($value->description)}}
		                    </button>
                        <input type="hidden"  name="report_id" class="report_hidden" value="{{($key == 0) ? $value->id : ''}}">
		                    <input type="hidden"  name="user_content_id" class="user_content_id">
		                  </div>
	                  	@endforeach
                  	@endif
                  
                  <div class="col-md-2"></div>
                </div>
                <div class="border-bottom mb-4"></div>
                <div class="row">
                  <div class="col-md-12 mb-4 text-center">
                    <button type="submit" class="btn btn-primary rounded-pill btn_report_send btn_reporting">
                      Submit
                    </button>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div> 
@section('script')
@parent
<script type="text/javascript">
	function report(key,id,user_id){
        $( "#reportingModal").modal({
            backdrop: 'static',
            keyboard: false
        });
        $('.user_content_id').val(id);
     }
     $('.report').click(function(){
     	$('.report').removeClass('btn_reporting');
     	$(this).addClass('btn_reporting');
     	$('.report_hidden').val($(this).data('value'));
     })
     $('.btn_report_send').click(function(){
        $('.btn_report_send').html(loader());
        $('.btn_report_send').attr('disabled',true);

     	  // $.ajax({
        //       url: "{{route('user.report.save')}}",
        //       method: 'post',
        //       data: {'report_id':$('.report_hidden').val(),'user_content_id':$('.user_content_id').val()},
        //       dataType: "json",
        //       success: function(response){
        //         $('.btn_report_send').html('Submit');
        //         $('.btn_report_send').attr('disabled',false);
        //         if (response.status == 1){
        //             var ht = '<ul>';
        //             ht += "<li class='alert alert-success'>"+response.message+"</li>";
        //             setTimeout(function(){ $(".report_server_response").html(''); }, 3000);
        //             $(".report_server_response").html(ht);
        //         }
        //         if (response.status == 0){
        //             var ht = '<ul>';
        //               ht += "<li class='alert alert-danger'>"+response.message+"</li>";
        //              setTimeout(function(){ $(".report_server_response").html(''); }, 3000);
        //             $(".report_server_response").html(ht);
        //         }
        //       }
        // });
        axios({
              method: 'post',
              url: "{{route('user.report.save')}}",
              data:{'report_id':$('.report_hidden').val(),'user_content_id':$('.user_content_id').val()},
              responseType: 'json'
            }).then(function (response) {
              $('.btn_report_send').html('Submit');
                $('.btn_report_send').attr('disabled',false);
                if (response.data.status == 1){
                    var ht = '<ul>';
                    ht += "<li class='alert alert-success'>"+response.data.message+"</li>";
                    setTimeout(function(){ $(".report_server_response").html(''); }, 3000);
                    $(".report_server_response").html(ht);
                }
                if (response.data.status == 0){
                    var ht = '<ul>';
                      ht += "<li class='alert alert-danger'>"+response.data.message+"</li>";
                     setTimeout(function(){ $(".report_server_response").html(''); }, 3000);
                    $(".report_server_response").html(ht);
                }
            }).catch(function (error) {
              $('.btn_report_send').html('Submit');
              $('.btn_report_send').attr('disabled',false);
              $('#signUpModal').modal("show"); 
              $('#reportingModal').modal("hide");
      }).finally(function () {
              // $('.like_spinner_'+key).hide();
      });

     })
</script>
@endsection
 