routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */

Route::get('/clear-cache', function () {
    $exitCode = Artisan::call('cache:clear');
    return "Cache is cleared";
});

Route::get('/clear-config', function () {
    $exitCode = Artisan::call('config:clear');
    return "Configuration Cache is cleared";
});
Route::get('/clear-route', function () {
    $exitCode = Artisan::call('route:clear');
    return "Route Cache is cleared";
});

Route::get('/clear-view', function () {
    $exitCode = Artisan::call('view:clear');
    return "View Cache is cleared";
});
Route::get("/time", function () {
    return date("h:i:s a", $_SERVER['REQUEST_TIME']);
});

Route::get('scheduler', 'ArtisanController@handle');

Route::get('privacy', 'FrontEndController@privacy')->name('privacy');
Route::get('term-condition', 'FrontEndController@termOfCondition')->name('term-condition');
Route::get('/', 'HomeController@index')->name('home');

Route::resource('albums', 'AlbumsController');
Route::resource('photos', 'PhotosController');

// Socail Logins
Route::get('login/{provider}', 'SocailAuthController@redirectToProvider');
Route::get('login/{provider}/callback', 'SocailAuthController@handleProviderCallback');

Route::get('get-competition-detail', 'UserController@getDetailCompetition')->name('user.get-competition-detail');

Route::get('get-competiton-all/{cat}', 'UserController@show_all')->name('user.show-all');
Route::post('user/do-login', 'UserController@doLogin')->name('user.doLogin');
Route::post('user/verify-code', 'UserController@verifyPhoneNumber')->name('user.verify_phone_number');
Route::get('user/role', 'UserController@userRole')->name('user.role');
Route::post('user/do-register', 'UserController@doregister')->name('user.doRegister');
Route::post('user/add-user-detail', 'UserController@addUserDetail')->name('user.addUserDetail');
Route::get('get-states', 'UserController@getStates')->name('get-states');
Route::get('voting', ['as' => 'voting', 'uses' => 'UserController@votingMedia']);
Route::post('comment', ['as' => 'comment', 'uses' => 'CompetitionController@getCommentPost']);
Route::get('comment_all', ['as' => 'comment_all', 'uses' => 'CompetitionController@getAllCommentPost']);
Route::group(['middleware' => 'auth', 'prefix' => 'user', 'as' => 'user.'], function () {
    Route::get('do-logout', ['as' => 'doLogout', 'uses' => 'UserController@doLogout']);
    Route::get('dashboard', ['as' => 'dashboard', 'uses' => 'UserController@dashboard']);
    Route::post('competitions', ['as' => 'competitions', 'uses' => 'UserController@ShowDatatable']);
    Route::get('profile', ['as' => 'profile', 'uses' => 'UserFollowController@index']);
    Route::post('follow', ['as' => 'follow', 'uses' => 'UserFollowController@followUser']);
    Route::get('getShareableLink', ['as' => 'getShareableLink', 'uses' => 'UserController@getShareableLink']);
    Route::get('getShareableLinkCount', ['as' => 'getShareableLinkCount', 'uses' => 'UserController@getShareableLinkCount']);
    Route::get('getShareableLinkCountAll', ['as' => 'getShareableLinkCountAll', 'uses' => 'UserController@getShareableLinkCountAll']);

    Route::group(['prefix' => 'content', 'as' => 'content.'], function () {
        Route::post('add', ['as' => 'add', 'uses' => 'UserContentController@addContent'])->middleware(['role:user']);
        Route::get('get-genres', ['as' => 'get-genres', 'uses' => 'UserContentController@getGenres']);
        Route::post('add_like', ['as' => 'add_like', 'uses' => 'UserContentController@addUserLikes']);
        Route::post('judge', ['as' => 'judge', 'uses' => 'UserContentController@competitionUserJudge']);
        Route::get('get-user-competition', ['as' => 'get-user-competition', 'uses' => 'UserContentController@getUserCompetition']);
    });
    Route::group(['prefix' => 'competition', 'as' => 'competition.'], function () {
        Route::get('create', ['as' => 'create', 'uses' => 'CompetitionController@index'])->middleware(['role:user|fan|agent|sponsor']);
        Route::get('get-public-competition', ['as' => 'get-public-competition', 'uses' => 'CompetitionController@getPublicCompetition']);
        Route::get('get-public-competition-detail', ['as' => 'get-public-competition-detail', 'uses' => 'CompetitionController@getPublicCompetitionDetail']);
        Route::post('save', ['as' => 'save', 'uses' => 'CompetitionController@saveCompetion'])->middleware(['role:user|fan|agent|sponsor']);
        Route::get('private/join', ['as' => 'private_join', 'uses' => 'CompetitionController@joinPrivate']);
        Route::get('verify-code', ['as' => 'verify_code', 'uses' => 'CompetitionController@codeVerify']);
        Route::post('join_private_competition', ['as' => 'join_private_competition', 'uses' => 'CompetitionController@joinPrivateCompetition']);
        Route::post('join_public_competition', ['as' => 'join_public_competition', 'uses' => 'CompetitionController@joinPublicCompetition']);

    });
    Route::group(['prefix' => 'report', 'as' => 'report.'], function () {
        Route::post('save', ['as' => 'save', 'uses' => 'AbuseReportController@saveReport']);
    });
    Route::get('getAllActiveUsers', ['as' => 'getAllActiveUsers', 'uses' => 'HomeController@getUserDetails']);
});
Route::group(['prefix' => 'phone', 'as' => 'user.phone.'], function () {
    Route::post('send-verify', ['as' => 'send-verify', 'uses' => 'HomeController@sendVerifyCode']);
    Route::post('change_number', ['as' => 'change_number', 'uses' => 'HomeController@changeNumber']);
    Route::post('verify', ['as' => 'verify', 'uses' => 'HomeController@VerifyCode']);
});
/******************* Test Route *************/
Route::get('email-check', ['uses' => 'TestController@emailTest']);
Route::get('phone-test', ['uses' => 'TestController@phoneTest']);
Route::get('account-detail', ['uses' => 'TestController@index']);
Route::get('testing', ['uses' => 'TestController@competitionDetailForTesting']);
Route::get('video-test', ['uses' => 'TestController@videoTest']);
Route::get('pp', ['uses' => 'TestController@pp']);

app/Http/Controllers/AlbumsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Modals\Album;

class AlbumsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $albums=Album::with('photos')->get();
        return view('albums.index')->with('albums',$albums);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('albums.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        $filewithextention=$request->file('cover_image')->getClientOriginalName();
        $filename=pathinfo($filewithextention,PATHINFO_FILENAME);
        $extention=$request->file('cover_image')->getClientOriginalExtension();
        $path = $filename . '_'. time(). '.' . $extention;
        $imagepath=$request->file('cover_image')->storeAs('public/album_covers',$path);


        $album=new Album();
        $album->name=$request->input('name');
        $album->description=$request->input('description');
        $album->cover_image=$imagepath;
        $album->save();

        session()->flash('message', 'Post was created!');

        return redirect()->route('albums.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/albums/create.blade.php
@extends('layouts.app')

@section('content')

<div class="container">

<h2>create new album</h2>

<form method="post" action="{{route('albums.store')}}" enctype="multipart/form-data">
@csrf
  <div class="form-group">
    <label for="name">Name</label>
    <input type="text" class="form-control" id="name" name="name"  placeholder="Enter email">
  </div>

  <div class="form-group">
    <label for="description">Description</label>
    <input type="text" class="form-control" id="description" name="description"  placeholder="Enter description">
  </div>

  <div class="form-group">
    <label for="cover_image">Cover Image</label>
    <input type="file" class="form-control" id="cover_image" name="cover_image"  >
  </div>
  
  <button type="submit" class="btn btn-primary">Submit</button>
</form>

</div>
@endsection

resources/views/albums/index.blade.php
@extends('layouts.app')

@section('content')
<main role="main">

      <section class="jumbotron text-center">
        <div class="container">
          <h1 class="jumbotron-heading">Album </h1>

        </div>
      </section>

      <div class="album py-5 bg-light">
        <div class="container">
        @if(count($albums) > 0)
          <div class="row">
          @foreach($albums as $album)
            <div class="col-md-4">
              <div class="card mb-4 box-shadow">
               <img src="{!!checkImage(asset('storage/album_covers/'. $album->cover_image),'no_image.jpg')!!}" alt="">
                <div class="card-body">
                  <p class="card-text">{{$album->description}}</p>
                  <div class="d-flex justify-content-between align-items-center">
                    <div class="btn-group">
                      <button type="button" class="btn btn-sm btn-outline-secondary">View</button>
                      <button type="button" class="btn btn-sm btn-outline-secondary">Edit</button>
                    </div>
                    <small class="text-muted">{{$album->name}}</small>
                  </div>
                </div>
              </div>
            </div>

            @endforeach

          </div>

          @else
          <h3>No album found</h3>

          @endif
        </div>
      </div>

    </main>

@endsection